language: csharp
solution: linq-editor.sln
install:
  - nuget restore linq-editor.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release linq-editor.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe -exclude=Database ./LinqEditor.Core.Tests/bin/Release/LinqEditor.Core.Tests.dll ./LinqEditor.Core.Session.Tests/bin/Release/LinqEditor.Core.Session.Tests.dll ./LinqEditor.Core.CodeAnalysis.Tests/bin/Release/LinqEditor.Core.CodeAnalysis.Tests.dll ./LinqEditor.Core.Templates.Tests/bin/Release/LinqEditor.Core.Templates.Tests.dll
