language: csharp
solution: linq-editor.sln
install:
  - nuget restore linq-editor.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release linq-editor.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./LinqEditor.Core.CodeAnalysis.Tests/bin/Release/LinqEditor.Core.CodeAnalysis.Tests.dll ./LinqEditor.Utility.Tests/bin/Release/LinqEditor.Utility.Tests.dll
