build:
  project: linq-editor.sln
configuration: Debug
platform: Any CPU

services: mssql2012sp1

environment:
  COVER_FOLDER: TestCoverage
  COVERALLS_REPO_TOKEN:
    secure: irQMjb5YkoBrSl1u1ayE+MqGUpvDDnOPmFVe3L+Tgvse71DfQhFU4iL5XHPOtpxd

artifacts:
  - path: LinqEditor.$(APPVEYOR_BUILD_VERSION).zip
    name: LinqEditor $(CONFIGURATION)

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(APPVEYOR_BUILD_VERSION)

before_build: nuget restore

after_build: 7z a LinqEditor.%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\LinqEditor.UI.WinForm\bin\Debug

test_script:
  - .\runcover.bat
  - ps: >-
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

