environment:
  COVER_FOLDER: TestCoverage
  COVERALLS_REPO_TOKEN:
    secure: irQMjb5YkoBrSl1u1ayE+MqGUpvDDnOPmFVe3L+Tgvse71DfQhFU4iL5XHPOtpxd

before_build:
  - nuget restore

after_build:
  - 7z a LinqEditor.%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\LinqEditor.UI.WinForm\bin\Debug

artifacts:
  - path: LinqEditor.$(APPVEYOR_BUILD_VERSION).zip
    name: LinqEditor

test_script:
  - .\runcover.bat
  - ps: >-
      Write-Host "FOOBAR"
      Write-Host "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)"
      Write-Host (Resolve-Path .\TestResult.xml)

services:
  - mssql2012sp1

configuration:
  - Debug

build:
  project: linq-editor.sln

assembly_info:
  patch: true
  file: LinqCore*\**\AssemblyInfo.cs
  assembly_version: $(APPVEYOR_BUILD_VERSION)
