build:
  project: linq-editor.sln
configuration: Release
platform: Any CPU
services: mssql2012sp1
# version = build id
version: 0.1.0.{build}

environment:
  COVER_FOLDER: TestCoverage
  COVERALLS_REPO_TOKEN:
    secure: irQMjb5YkoBrSl1u1ayE+MqGUpvDDnOPmFVe3L+Tgvse71DfQhFU4iL5XHPOtpxd

artifacts:
  - path: LinqEditor-$(APPVEYOR_BUILD_VERSION).zip
    name: LinqEditor

assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build: nuget restore

after_build: 
  - cd %APPVEYOR_BUILD_FOLDER%\LinqEditor.UI.WinForm\bin\%CONFIGURATION%
  - 7z a %APPVEYOR_BUILD_FOLDER%\LinqEditor-%APPVEYOR_BUILD_VERSION%.zip *.config *.exe *.dll mscorlib.xml System.Core.xml System.Data.xml System.xml System.Xml.xml
  - cd %APPVEYOR_BUILD_FOLDER%

test_script:
  - .\packages\OpenCover.4.5.3723\OpenCover.Console.exe -target:runtests.bat -register:user -filter:"+[LinqEditor*]* -[*Test*]* -[*UI.WinForm]* -[*Templates]*Base" -output:.\%COVER_FOLDER%\TestCoverage.xml -returntargetcode
  - .\packages\coveralls.io.1.3.4\tools\coveralls.net.exe %APPVEYOR_BUILD_FOLDER%\%COVER_FOLDER%\TestCoverage.xml