before_build:
  - nuget restore
build:
  project: .\linq-editor.sln
  verbosity: minimal
services:
  - mssql2012sp1
configuration:
  - Release
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)