build:
  project: linq-editor.sln
configuration: Debug
platform: Any CPU
version: 0.1.0.{build}

services: mssql2012sp1

environment:
  COVER_FOLDER: TestCoverage
  COVERALLS_REPO_TOKEN:
    secure: irQMjb5YkoBrSl1u1ayE+MqGUpvDDnOPmFVe3L+Tgvse71DfQhFU4iL5XHPOtpxd

artifacts:
  - path: LinqEditor.$(APPVEYOR_BUILD_VERSION).zip
    name: LinqEditor

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '0.1.0.0'
  assembly_file_version: '{version}'

before_build: nuget restore

after_build: 
  - 7z a LinqEditor.%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\LinqEditor.UI.WinForm\bin\Debug\*

test_script:
  - .\runcover.bat
  - ps: >-
      $url = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)";
      $wc = New-Object 'System.Net.WebClient';
      $wc.UploadFile($url, (Resolve-Path .\TestResult.xml));

