before_build:
  - nuget restore
services:
  - mssql2012sp1
configuration:
  - Release
build:
  project: linq-editor.sln
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)
