environment:
  COVER_FOLDER: TestCoverage
  COVERALLS_REPO_TOKEN:
    secure: irQMjb5YkoBrSl1u1ayE+MqGUpvDDnOPmFVe3L+Tgvse71DfQhFU4iL5XHPOtpxd

before_build:
  - nuget restore

services:
  - mssql2012sp1

configuration:
  - Release

build:
  project: linq-editor.sln

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)

# we'll just upload the output from the OpenCover run, instead of running the tests twice
test: off

after_build:
  - .\runcover.bat
  - ps:$wc = New-Object 'System.Net.WebClient'
  - ps:$wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $($env:COVER_FOLDER)))
