build:
  project: linq-editor.sln
configuration: Release
platform: Any CPU
services: mssql2012sp1
# version = build id
version: 0.1.0.{build}

environment:
  COVER_FOLDER: TestCoverage
  COVERALLS_REPO_TOKEN:
    secure: irQMjb5YkoBrSl1u1ayE+MqGUpvDDnOPmFVe3L+Tgvse71DfQhFU4iL5XHPOtpxd

artifacts:
  - path: LinqEditor-$(APPVEYOR_BUILD_VERSION).zip
    name: LinqEditor

assembly_info:
  patch: true
  file: SharedAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build: nuget restore

after_build: 
  - cd %APPVEYOR_BUILD_FOLDER%\LinqEditor.UI.WinForm\bin\%CONFIGURATION%
  - 7z a %APPVEYOR_BUILD_FOLDER%\LinqEditor-%APPVEYOR_BUILD_VERSION%.zip *.config *.exe *.dll mscorlib.xml System.Core.xml System.Data.xml System.xml System.Xml.xml
  - cd %APPVEYOR_BUILD_FOLDER%

test_script:
  - .\runcover.bat
  - ps: >-
      $url = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)";
      $wc = New-Object 'System.Net.WebClient';
      $wc.UploadFile($url, (Resolve-Path .\TestResult.xml));

