# version = build id
version: 0.1.0.{build}
test: off # this turns of AppVeyor automatic searching for test-assemblies
build: off # no msbuild build

# see https://github.com/enricosada/fsharp-dotnet-cli-samples/blob/master/appveyor.yml
install:
  - ps: .\scripts\show-dotnet-info.ps1
  # Download install script to install .NET cli in .dotnet dir
  - ps: mkdir -Force ".\scripts\obtain\" | Out-Null
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/install.ps1" -OutFile ".\scripts\obtain\install.ps1"
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"
  - ps: '& .\scripts\obtain\install.ps1 -Channel "preview" -version "$env:CLI_VERSION" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  # add dotnet to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
    - ps: push-location query-engine
    - ps: dotnet restore
    - ps: dotnet build
    - ps: pop-location query-engine
